import { Mentor, Student, PaymentPlan, ChatMessage, Review } from '../types';

// In a real app, this would come from an API
export const MOCK_MENTORS: Mentor[] = [
  { id: 1, name: 'Zhang Wei (张伟)', university: 'Stanford University', major: 'Computer Science', category: 'STEM', region: 'USA', price: 150, verified: { name: true, school: true }, avatar: 'https://picsum.photos/id/1027/200/200', experience: 'Tsinghua University alumnus, now at Stanford. Specialized in helping students from Chinese universities with their US CS grad school applications.', degree: 'PhD Candidate', rating: 4.9, reviewCount: 32, role: 'mentor', profile: { university: 'Stanford University', major: 'Computer Science', degree: 'PhD Candidate', background: 'Tsinghua University alumnus, now at Stanford. Research focus on Natural Language Processing.', services: 'SOP crafting for AI/ML tracks, technical interview prep (FAANG level), selecting research-focused vs. professional master\'s programs.'} },
  { id: 2, name: 'Dr. Emily White', university: 'London School of Economics', major: 'Finance', category: 'Business & Economics', region: 'UK', price: 180, verified: { name: true, school: true }, avatar: 'https://picsum.photos/id/1011/200/200', experience: 'Peking University alum, now at LSE. Expert in G5 university applications for finance and economics majors.', degree: 'MSc', rating: 5.0, reviewCount: 45, role: 'mentor', profile: { university: 'London School of Economics', major: 'Finance', degree: 'MSc', background: 'Peking University alum, now working in investment banking in London. Expert in G5 university applications for finance and economics majors.', services: 'Personal statement crafting, interview coaching for Oxbridge & LSE, CV tailoring for finance roles.'} },
  { id: 3, name: 'Wang Fang (王芳)', university: 'University of Toronto', major: 'Data Science', category: 'STEM', region: 'Canada', price: 120, verified: { name: true, school: false }, avatar: 'https://picsum.photos/id/1012/200/200', experience: 'Fudan University graduate, currently studying Data Science in Toronto. Strong background in Canadian university applications.', degree: 'MSc Candidate', rating: 4.8, reviewCount: 18, role: 'mentor', profile: { university: 'University of Toronto', major: 'Data Science', degree: 'MSc Candidate', background: 'Fudan University graduate with experience in the Canadian tech industry.', services: 'Navigating the Canadian university application system, co-op program guidance, and visa application support.'} },
  { id: 4, name: 'Liu Yang (刘洋)', university: 'ETH Zurich', major: 'Electrical Engineering', category: 'STEM', region: 'Europe', price: 160, verified: { name: true, school: true }, avatar: 'https://picsum.photos/id/1013/200/200', experience: 'SJTU alumnus, now at ETH Zurich. Focuses on helping engineering students apply to top European technical universities.', degree: 'PhD', rating: 4.9, reviewCount: 25, role: 'mentor', profile: { university: 'ETH Zurich', major: 'Electrical Engineering', degree: 'PhD', background: 'Shanghai Jiao Tong University alumnus with research experience at a leading European lab.', services: 'Application strategies for EU technical universities (ETH, EPFL, TU Delft), research proposal writing, and scholarship application guidance.'} },
  { id: 5, name: 'Chen Jing (陈静)', university: 'National University of Singapore', major: 'Business Analytics', category: 'Business & Economics', region: 'Asia', price: 130, verified: { name: false, school: false }, avatar: 'https://picsum.photos/id/1015/200/200', experience: 'Graduated from Zhejiang University. Familiar with the application process for top business schools in Singapore and Hong Kong.', degree: 'MSc', rating: 4.7, reviewCount: 12, role: 'mentor', profile: { university: 'National University of Singapore', major: 'Business Analytics', degree: 'MSc', background: 'Zhejiang University graduate, now a data analyst in Singapore.', services: 'Guidance on applications to top business schools in Singapore (NUS, NTU) and Hong Kong (HKU, HKUST), including video essay preparation.'} },
  { id: 6, name: 'Robert Smith', university: 'Harvard Business School', major: 'Business Administration (MBA)', category: 'Business & Economics', region: 'USA', price: 250, verified: { name: true, school: true }, avatar: 'https://picsum.photos/id/10/200/200', experience: 'Former consultant at McKinsey. Specializes in MBA applications, especially for candidates with non-traditional backgrounds.', degree: 'MBA', rating: 5.0, reviewCount: 58, role: 'mentor', profile: { university: 'Harvard Business School', major: 'Business Administration (MBA)', degree: 'MBA', background: 'Former consultant at McKinsey with a background in engineering.', services: 'M7 MBA application strategy, GMAT preparation, essay editing, and mock interviews with a focus on case studies.'} },
  { id: 7, name: 'Maria Garcia', university: 'Technical University of Munich', major: 'Mechanical Engineering', category: 'STEM', region: 'Europe', price: 155, verified: { name: true, school: true }, avatar: 'https://picsum.photos/id/22/200/200', experience: 'Automotive industry professional with deep knowledge of German technical university applications and career paths.', degree: 'PhD', rating: 4.8, reviewCount: 22, role: 'mentor', profile: { university: 'Technical University of Munich', major: 'Mechanical Engineering', degree: 'PhD', background: 'Experienced engineer in the German automotive industry.', services: 'Navigating the German TU9 university system, preparing documents for German universities, and providing career advice for engineers in Europe.'} },
  { id: 8, name: 'Aisha Khan', university: 'University College London', major: 'Psychology', category: 'Humanities & Social Sciences', region: 'UK', price: 140, verified: { name: true, school: false }, avatar: 'https://picsum.photos/id/25/200/200', experience: 'Clinical psychology researcher with expertise in crafting compelling personal statements for social science programs.', degree: 'MSc', rating: 4.9, reviewCount: 19, role: 'mentor', profile: { university: 'University College London', major: 'Psychology', degree: 'MSc', background: 'Clinical psychology researcher with publications in peer-reviewed journals.', services: 'Crafting personal statements for social science and psychology programs, research proposal guidance, and preparing for academic interviews.'} },
  { id: 9, name: 'Kenji Tanaka', university: 'New York University', major: 'Marketing', category: 'Business & Economics', region: 'USA', price: 170, verified: { name: true, school: true }, avatar: 'https://picsum.photos/id/31/200/200', experience: 'Works in brand management for a Fortune 500 company. Helps students break into competitive business master\'s programs.', degree: 'MSc', rating: 4.7, reviewCount: 30, role: 'mentor', profile: { university: 'New York University', major: 'Marketing', degree: 'MSc', background: 'Brand manager at a Fortune 500 company in NYC.', services: 'Marketing program application strategy, resume building for business roles, and networking advice for the US job market.'} },
  { id: 10, name: 'Chloe Kim', university: 'Johns Hopkins University', major: 'Biology', category: 'STEM', region: 'USA', price: 165, verified: { name: true, school: true }, avatar: 'https://picsum.photos/id/35/200/200', experience: 'Focuses on pre-med and biological sciences PhD tracks. Extensive experience with research-heavy applications.', degree: 'PhD Candidate', rating: 4.9, reviewCount: 28, role: 'mentor', profile: { university: 'Johns Hopkins University', major: 'Biology', degree: 'PhD Candidate', background: 'Researcher in molecular biology at a world-renowned lab.', services: 'Guidance for pre-med and biological sciences PhD tracks, writing research statements, and contacting potential supervisors.'} },
  { id: 11, name: 'James Brown', university: 'University of Chicago', major: 'Public Policy', category: 'Humanities & Social Sciences', region: 'USA', price: 175, verified: { name: true, school: true }, avatar: 'https://picsum.photos/id/42/200/200', experience: 'Government and NGO background. Guides students aiming for careers in public service and international relations.', degree: 'MPP', rating: 4.8, reviewCount: 35, role: 'mentor', profile: { university: 'University of Chicago', major: 'Public Policy', degree: 'MPP', background: 'Policy analyst with experience at a DC-based think tank.', services: 'Essay editing for public policy and international relations programs, quantitative skills resume highlighting, and career coaching for public service roles.'} },
  { id: 12, name: 'Isabella Rossi', university: 'Rhode Island School of Design', major: 'Fine Arts (MFA)', category: 'Arts & Design', region: 'USA', price: 135, verified: { name: true, school: false }, avatar: 'https://picsum.photos/id/45/200/200', experience: 'Practicing artist and curator. Specializes in portfolio reviews and artist statements for top art schools.', degree: 'MFA', rating: 4.9, reviewCount: 15, role: 'mentor', profile: { university: 'Rhode Island School of Design', major: 'Fine Arts (MFA)', degree: 'MFA', background: 'Practicing artist and curator with work exhibited internationally.', services: 'Portfolio development and review, crafting compelling artist statements, and selecting the right MFA program for your artistic practice.'} },
  { id: 13, name: 'Michael Chen', university: 'University of Waterloo', major: 'Computer Science', category: 'STEM', region: 'Canada', price: 145, verified: { name: true, school: true }, avatar: 'https://picsum.photos/id/48/200/200', experience: 'Software engineer at a major tech company. Focus on co-op programs and technical interview preparation for Canadian universities.', degree: 'MSc', rating: 4.8, reviewCount: 41, role: 'mentor', profile: { university: 'University of Waterloo', major: 'Computer Science', degree: 'MSc', background: 'Software engineer at Amazon and a proud Waterloo alumnus.', services: 'Co-op program application strategy, technical interview preparation (LeetCode style), and advice on the Canadian tech job market.'} },
  { id: 14, name: 'Olivia Williams', university: 'University of Cambridge', major: 'Finance', category: 'Business & Economics', region: 'UK', price: 185, verified: { name: true, school: true }, avatar: 'https://picsum.photos/id/54/200/200', experience: 'Investment banking analyst in London. Oxbridge application specialist with a focus on quantitative finance.', degree: 'MPhil', rating: 5.0, reviewCount: 39, role: 'mentor', profile: { university: 'University of Cambridge', major: 'Finance', degree: 'MPhil', background: 'Investment banking analyst at Goldman Sachs in London.', services: 'Oxbridge application specialist for quantitative finance and economics, guidance on challenging entrance exams, and mock interview preparation.'} },
  { id: 15, name: 'David Lee', university: 'Columbia University', major: 'Data Science', category: 'STEM', region: 'USA', price: 160, verified: { name: true, school: true }, avatar: 'https://picsum.photos/id/57/200/200', experience: 'Data scientist in the tech industry. Expertise in applications for Ivy League data science and analytics programs.', degree: 'MSc', rating: 4.9, reviewCount: 29, role: 'mentor', profile: { university: 'Columbia University', major: 'Data Science', degree: 'MSc', background: 'Data scientist at Netflix with a focus on recommendation systems.', services: 'Ivy League data science program applications, project portfolio advice, and preparation for technical data science interviews.'} },
  { id: 16, name: 'Sophie Dubois', university: 'Delft University of Technology', major: 'Architecture', category: 'Arts & Design', region: 'Europe', price: 150, verified: { name: false, school: true }, avatar: 'https://picsum.photos/id/61/200/200', experience: 'Architect at a leading European firm. Provides guidance on portfolio creation and applications to EU architecture schools.', degree: 'MArch', rating: 4.7, reviewCount: 11, role: 'mentor', profile: { university: 'Delft University of Technology', major: 'Architecture', degree: 'MArch', background: 'Architect at OMA, a leading European firm.', services: 'Architectural portfolio creation and curation, application strategies for top European architecture schools (TU Delft, ETH), and software skills guidance.'} },
  { id: 17, name: 'William Taylor', university: 'London School of Economics', major: 'Law (LLM)', category: 'Humanities & Social Sciences', region: 'UK', price: 190, verified: { name: true, school: true }, avatar: 'https://picsum.photos/id/65/200/200', experience: 'Practicing corporate lawyer. Helps international students navigate the complexities of applying to top UK law programs.', degree: 'LLM', rating: 4.8, reviewCount: 24, role: 'mentor', profile: { university: 'London School of Economics', major: 'Law (LLM)', degree: 'LLM', background: 'Corporate lawyer at a Magic Circle firm in London.', services: 'Navigating the UK LLM application process, writing effective personal statements for law school, and providing career advice for the legal sector.'} },
  { id: 18, name: 'Daniel Kim', university: 'MIT', major: 'Economics', category: 'Business & Economics', region: 'USA', price: 195, verified: { name: true, school: true }, avatar: 'https://picsum.photos/id/75/200/200', experience: 'PhD in Economics with a focus on econometrics. Assists students with highly quantitative and research-focused applications.', degree: 'PhD', rating: 5.0, reviewCount: 31, role: 'mentor', profile: { university: 'MIT', major: 'Economics', degree: 'PhD', background: 'Postdoctoral researcher in economics at the University of Chicago.', services: 'Guidance for top PhD programs in Economics, writing a Statement of Research Interests, and preparing for quantitative interviews.'} },
  { id: 19, name: 'Emma Wilson', university: 'Australian National University', major: 'Environmental Science', category: 'STEM', region: 'Australia', price: 130, verified: { name: true, school: false }, avatar: 'https://picsum.photos/id/82/200/200', experience: 'Climate policy advisor. Deep knowledge of the Australian university system and sustainability-related programs.', degree: 'MSc', rating: 4.8, reviewCount: 14, role: 'mentor', profile: { university: 'Australian National University', major: 'Environmental Science', degree: 'MSc', background: 'Climate policy advisor for the Australian government.', services: 'Navigating the Australian Group of Eight (Go8) university system, applying for sustainability-related programs, and career advice in the environmental sector.'} },
  { id: 20, name: 'Chen Hao (陈浩)', university: 'UIUC', major: 'Electrical Engineering', category: 'STEM', region: 'USA', price: 155, verified: { name: true, school: true }, avatar: 'https://picsum.photos/id/88/200/200', experience: 'Hardware engineer with experience at top semiconductor companies. Helps students with top US ECE program applications.', degree: 'MSc Candidate', rating: 4.9, reviewCount: 27, role: 'mentor', profile: { university: 'University of Illinois Urbana-Champaign', major: 'Electrical Engineering', degree: 'MSc Candidate', background: 'Hardware engineer at Nvidia with a focus on GPU architecture.', services: 'Guidance for top US ECE programs (UIUC, Michigan, etc.), resume tailoring for hardware roles, and interview prep for semiconductor companies.'} },
];

export const MOCK_STUDENT_USER: Student = {
  id: 21,
  name: 'Li Ming (李明)',
  role: 'student',
  avatar: 'https://picsum.photos/id/1018/200/200',
  verified: { name: false, school: false },
  profile: {
    university: 'Shanghai Jiao Tong University',
    major: 'Computer Science',
    degree: 'B.Eng',
    background: 'Current senior at SJTU with a GPA of 3.8/4.0. Strong interest in Machine Learning and Distributed Systems.',
    needs: 'Seeking guidance on Statement of Purpose and school selection for top 20 US MSCS programs.',
  },
  paymentMethods: [],
};

export const MOCK_MENTOR_USER: Mentor = MOCK_MENTORS[1]; // Dr. Emily White

export const MOCK_PAYMENT_PLAN: PaymentPlan = {
  studentId: 21,
  mentorId: 2,
  studentName: 'Li Ming',
  mentorName: 'Dr. Emily White',
  total: 9000,
  currency: 'CNY',
  milestones: [
    { id: 1, name: 'Statement of Purpose Draft & Polish', amount: 3000, dueDate: '2024-08-30', status: 'pending' },
    { id: 2, name: 'Resume/CV Writing & Review', amount: 3000, dueDate: '2024-09-30', status: 'locked' },
    { id: 3, name: 'Online Application System Guidance', amount: 3000, dueDate: '2024-10-30', status: 'locked' },
  ]
};

// Key is sorted user IDs: `${min(user1.id, user2.id)}-${max(user1.id, user2.id)}`
export const MOCK_CHATS: Record<string, ChatMessage[]> = {
  "2-21": [
    { senderId: 21, text: "Hello Dr. White, I saw your profile and I'm very interested in your mentorship for UK finance programs.", timestamp: "10:01 AM" },
    { senderId: 2, text: "Hi Li Ming, great to hear from you. I'd be happy to help. Can you tell me a bit about your background and what schools you're targeting?", timestamp: "10:03 AM" },
    { senderId: 21, text: "Of course! I'm graduating from SJTU with a B.Eng in Computer Science, but I want to pivot to quantitative finance. I'm aiming for LSE, Imperial, and Cambridge.", timestamp: "10:05 AM" },
  ],
  "1-21": [
      { senderId: 21, text: "Hi Zhang Wei, I'm a student from SJTU as well and need help with my US CS application.", timestamp: "Yesterday" },
      { senderId: 1, text: "Nice to meet a fellow alumnus! I specialize in that. Let's discuss your profile. What are your main concerns?", timestamp: "Yesterday" },
  ]
};

export const MOCK_REVIEWS: Record<number, Review[]> = {
  1: [ // Zhang Wei
    { id: 1, reviewerName: 'Student A', date: '2024-05-20', rating: 5, comment: 'Zhang Wei was incredibly helpful! His insights into the Stanford application process were invaluable. He helped me structure my SOP perfectly.'},
    { id: 2, reviewerName: 'Student B', date: '2024-04-12', rating: 4.5, comment: 'Great mentor. Very knowledgeable about the technical aspects of CS applications. Could be a bit more responsive at times, but overall very helpful.'},
  ],
  2: [ // Dr. Emily White
    { id: 3, reviewerName: 'Student C', date: '2024-06-01', rating: 5, comment: 'Dr. White is simply the best. Her experience in finance is evident, and she provided exceptional guidance for my LSE application. I got in! Thank you!'},
    { id: 4, reviewerName: 'Student D', date: '2024-05-15', rating: 5, comment: 'Her mock interviews were tougher than the real one. Extremely well-prepared and professional. Highly recommend.'},
    { id: 5, reviewerName: 'Student E', date: '2024-05-10', rating: 5, comment: 'She transformed my personal statement from a generic draft to a compelling story. Worth every penny.'},
  ],
  6: [ // Robert Smith
    { id: 6, reviewerName: 'Student F', date: '2024-05-28', rating: 5, comment: 'As someone from a non-business background, I was lost. Robert helped me frame my engineering experience as a strength for my MBA application. A true expert.'},
    { id: 7, reviewerName: 'Student G', date: '2024-03-30', rating: 5, comment: 'His advice on the GMAT and essay writing was spot on. I improved my score by 50 points and got into my dream school.'}
  ],
  13: [ // Michael Chen
    { id: 8, reviewerName: 'Student H', date: '2024-06-05', rating: 5, comment: 'Michael knows the Canadian tech scene inside and out. His advice on Waterloo\'s co-op system was fantastic.'},
  ]
};